## Oracle
#spring.datasource.hikari.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.hikari.jdbc-url: jdbc:oracle:thin:@orcldb_high?TNS_ADMIN=/Users/jules/Projects/lib/Wallet_orcldb/
#spring.datasource.hikari.username=${datasource.username}
#spring.datasource.hikari.password=${datasource.password}
server:
  port: 8070

spring:
  datasource:
    ##mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/molog?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: '0307'
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
