## Oracle
#spring.datasource.hikari.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.hikari.jdbc-url: jdbc:oracle:thin:@orcldb_high?TNS_ADMIN=/Users/jules/Projects/lib/Wallet_orcldb/
#spring.datasource.hikari.username=admin
#spring.datasource.hikari.password=dmswls0307JJ
server:
  port: 8080

spring:
  datasource:
    ##mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/molog?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 'chma0326@'
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
